### PR TITLE
Optimize images, sphere geometry

### PR DESCRIPTION
**Pull request by brianpeiris**

### CODE REVIEW

**Comment by brianpeiris** [comment]
Hmm, actually it looks like most of the images are duplicated in the `assets/models` directory now, so maybe you can ignore most of this pull request. I'm not exactly sure which images are in use.

**Comment by brianpeiris** [comment]
To summarize the changes here:
- Optimized all jpegs with `jpegoptim.exe -m90'
- Converted the texture used by chair.dae from png to jpg
- Converted flooringwoodlight.jpg to an actual jpg (apparently the existing jpg was not actually a jpg)
- Reduced the resolution of the sky sphere geometry

**Comment by brianpeiris** [comment]
Ideally we'd clean up any unused textures before trying to optimize them

**Comment by Enderthexen** [comment]
Awesome, thanks Brian! Weird. I had moved all the model images and models into the "models" folder and then removed them from assets and removed unneeded images and duplicates. I had also run all PNGs through PNGoo (PNGQuant) and Jpegoptim (with max quality of 90). It seems some (or all) of these changes didn't get committed/pushed. I had commited and pushed but then had issues with my repo locally so had removed the repo then re-cloned. Not sure if something happened there and the changes didn't carry over. Anyways, I'll go back through and remove duplicates and unused (and not plan to be used) images and models today.

**Pull request merged**
